--- !DirTarget
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/edipofederle/Documents/modelingParaEscrita/TesteVisualizacao/
pathToProfile: resources/smarty.profile.uml
pathToProfileConcern: resources/perfilConcerns.profile.uml