--- !DirTarget
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/edipofederle/Documents/modelingParaEscrita/TesteVisualizacao/
pathToProfile: /Users/edipofederle/Desktop/testesRuns/resources/smarty.profile.uml
pathToProfileConcern: /Users/edipofederle/Desktop/testesRuns/resources/perfilConcerns.profile.uml