--- !DirTarget
pathToTemplateModelsDirectory: /Users/elf/Desktop/templates/
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/elf/Documents/workspace/output/
pathToProfile: src/test/java/resources/agm_gerada/resources/smarty.profile.uml
pathToProfileConcern: src/test/java/resources/agm_gerada/resources/perfilConcerns.profile.uml
