--- !DirTarget
pathToTemplateModelsDirectory: /Users/elf/Desktop/templates/
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/elf/Documents/workspaceModeling/testeFinal/
pathToProfile: /Users/elf/mestrado/sourcesMestrado/arquitetura/src/test/java/resources/agm_gerada/resources/smarty.profile.uml
pathToProfileConcern: /Users/elf/mestrado/sourcesMestrado/arquitetura/src/test/java/resources/agm_gerada/resources/perfilConcerns.profile.uml
pathToProfileRelationships: /Users/elf/mestrado/sourcesMestrado/arquitetura/src/test/java/resources/agm_gerada/resources/relationships.profile.uml
pathToProfilePatterns: /Users/elf/Documents/workspaceModeling/profiles/patterns.profile.uml

