--- !DirTarget
pathToTemplateModelsDirectory: /Users/elf/Desktop/templates/
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/elf/Documents/workspaceModeling/testeFinal/
pathToProfile: src/test/java/resources/agm_gerada/resources/smarty.profile.uml
pathToProfileConcern: src/test/java/resources/agm_gerada/resources/perfilConcerns.profile.uml
pathToProfileRelationships: "src/test/java/resources/profiles/relationship.profile.uml"
