--- !DirTarget
directoryToSaveModels: manipulation/
directoryToExportModels: /Users/edipofederle/Documents/modelingParaEscrita/AGM_SAIDA/
pathToProfile: src/test/java/resources/agm_gerada/resources/smarty.profile.uml
pathToProfileConcern: src/test/java/resources/agm_gerada/resources/perfilConcerns.profile.uml